### ISSUE TITLE
Kernel module unable to compile with 4.7.0+ kenrel version

### ISSUE THREAD

**Issue by coolsandyforyou** [zrlio/softiwarp#6]
Getting compilation errors like, 
siw.h:419:19: error: fileld 'mpa_crc_hd' has incomplete type

apparently headers are different.

So which kernel version should we use for the current soft-iwarp module to be installed?

**Comment by zbeeble2** [comment]
I'm experiencing similar problems after I installed the 4.7+ kernel on my Centos 7 system (via rpm repository). Also tried compiling on Centos 6 running kernel 3.10.0-327.28.3 and received the following errors:

In file included from /root/softiwarp/kernel/siw_main.c:55:0:
/_root/softiwarp/kernel/siw_cm.h: In function ‘get_tcp_mss’:
/root/softiwarp/kernel/siw_cm.h:165:8: error: ‘struct tcp_sock’ has no member named ‘xmit_size_goal_segs’
  if (tp->xmit_size_goal_segs)
        ^
/root/softiwarp/kernel/siw_cm.h:166:12: error: ‘struct tcp_sock’ has no member named ‘xmit_size_goal_segs’
   return tp->xmit_size_goal_segs \* tp->mss_cache;
            ^
/root/softiwarp/kernel/siw_main.c: In function ‘siw_device_create’:
/root/softiwarp/kernel/siw_main.c:415:24: warning: assignment from incompatible pointer type [enabled by default]
  ofa_dev->query_device = siw_query_device;
                        ^
/root/softiwarp/kernel/siw_main.c:434:21: warning: assignment from incompatible pointer type [enabled by default]
  ofa_dev->create_cq = siw_create_cq;
                     ^
/root/softiwarp/kernel/siw_main.c:455:23: warning: assignment from incompatible pointer type [enabled by default]
  ofa_dev->process_mad = siw_no_mad;
                       ^
make[2]: **\* [/root/softiwarp/kernel/siw_main.o] Error 1
make[1]: **\* [_module_/root/softiwarp/kernel] Error 2
make[1]: Leaving directory `/usr/src/kernels/3.10.0-327.28.3.el7.x86_64'
make: **\* [modules] Error 2__

The only kernel I've had success with is the one I compiled to build softroce:
https://github.com/SoftRoCE/rxe-dev.  

Any assistance would be greatly appreciated.

**Comment by zbeeble2** [comment]
Update: running 4.7 kernel on Centos 7 image via elrepo rpm repository (need kernel-ml & kernel-ml-devel installed). Ran into problems compiling kernel (see above), but code from fork maintained by github user softfranklin:

https://github.com/slowfranklin/softiwarp

seems to work better. Still would like to compile on older kernels for Centos 6/Redhat 6 versions ... no luck so far.

**Comment by BernardMetzler** [comment]
Sorry for being unresponsive on this for some time. I am swamped with my real jobs duties these days. I'll try to look into fixing siw for newer kernels sometimes next week.

**Comment by BernardMetzler** [comment]
I branched off older kernels into 'siw-pre-4.4' and updated 'master' to compile on kernel 4.8.
